-- =====================================================================
-- data-mau.sql - Script chen DU LIEU MAU cho CSDL vnpt_billing
-- =====================================================================
-- Phase 0: file nay CO CHU DINH de rong (xem chu thich trong schema.sql).
--
-- LUU Y QUAN TRONG: toan bo du lieu se chen o day la DU LIEU MAU TU SINH
-- phuc vu hoc tap, KHONG phai du lieu that cua bat ky nha mang nao.
-- =====================================================================
